### ISSUE TITLE
为什么你的gif和代码里面的内容不符的呀兄弟

### ISSUE THREAD

**Issue by Jun19** [wangeason/CollagesView#2]

**Comment by wangeason** [comment]
因为GIF是原来的app的截屏，有配合这个lib的UI，比如调整这个view的一些参数，代码里面是后来我只把我做的这个library放出来了，不过gif用到的接口都在

**Comment by Jun19** [comment]
首先很感谢你的回复！其次我还有个疑问就是 你的那一些模板布局是根据什么来生成的呢 谢谢

**Comment by wangeason** [comment]
val DEFAULT_POSITION, 左上角坐标0，0， 右下角1000，1000。每个图片的顶点的位置，顺时针，x1,y1,x2,y2,x3,y3,x4,y4

**Comment by Jun19** [comment]
谢谢！
